# Site settings
title: "Working Title"
email: indevilduality@gmail.com
description: "learning how to play with a blog theme"
baseurl: ""
url: 
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "URL"
github_repository:  
addthis_id: ra-513c6fa83da6ec67
post_limit: 10

# Social usernames/URLs
twitter_username: 
github_username:   
instagram_username: 
reddit_username: 
linkedin_link:   
google_plus_link:   
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"#URL#">TESTER test</a>"
footer_right: "&lt;/&gt; on <a href=\" \">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
